data_condition = [
  {
    title: "Ослеплённый",
    icon: "one-eyed",
    subtitle: "Вы не можете видеть",
    description: "Вы не можете видеть",
    reference: "PHB, стр. 290.",
    bullets: [
      "You automatically fail any ability check which requires sight.",
      "You have disadvantage on attack rolls.",
      "Attack rolls against you have advantage.",
    ],
  },
  {
    title: "Очарованный",
    icon: "smitten",
    subtitle: "Вы очарованы",
    description: "Вы очарованы другим существом",
    reference: "PHB, стр. 290.",
    bullets: [
      "You can't attack your charmer or target them with harmful abilities or magical effects.",
      "Your charmer has advantage on ability checks to interact socially with you.",
    ],
  },
  {
    title: "Оглохший",
    icon: "elf-ear",
    subtitle: "Вы не можете слышать",
    description: "Вы не можете слышать",
    reference: "PHB, стр. 290.",
    bullets: [
      "You automatically fail any ability check which requires hearing.",
    ],
  },
  {
    title: "Истощение",
    icon: "crawl",
    subtitle: "Вы истощены",
    description: "Истощение делится на шесть степеней",
    reference: "PHB, стр. 291.",
    bullets: [
      "<table><tr><th>Степень</th><th></th><th></th><th style='text-align:left'>Эффект</th></tr><tr><td>1</td><td></td><td></td><td>Помеха при проверке характеристик</td></tr><tr><td>2</td><td></td><td></td><td>Скорость уменьшается вдвое</td></tr><tr><td>3</td><td></td><td></td><td>Помеха бри бросках атаки и спасбросках</td></tr><tr><td>4</td><td></td><td></td><td>Максимум хитов уменьшается вдвое</td></tr><tr><td>5</td><td></td><td></td><td>Скорость снижется до 0</td></tr><tr><td>6</td><td></td><td></td><td>Смерть</td></tr></table>",
      "На существо воздействуют эффекты не только текущей степени истощения, но и более слабых степеней.",
      "Продолжительный отдых снижает степень истощения на 1, при условии, что существо что-нибудь съест или выпьет.",
      "Также, воскрешение из мёртвых снижает степень истощения воскрешённого существа на 1.",
    ],
  },
  {
    title: "Испуганный",
    icon: "sharp-smile",
    subtitle: "Вы испуганны",
    description: "Вы испуганны",
    reference: "PHB, стр. 290.",
    bullets: [
      "You have disadvantage on ability checks and attack rolls while the source of your fear is within line of sight.",
      "You can't willingly move closer to the source of your fear.",
    ],
  },
  {
    title: "Схваченный",
    icon: "grab",
    subtitle: "Вы схвачены",
    description: "Вы схвачены",
    reference: "PHB, стр. 290.",
    bullets: [
      "Your speed becomes 0, and you can't benefit from any bonus to your speed.",
      "The condition ends if your grappler is incapacitated.",
      "The condition also ends if you are removed from the reach of your grappler.",
    ],
  },
  {
    title: "Недееспособный",
    icon: "internal-injury",
    subtitle: "Вы не можете совершать действия и реакции",
    description: "Вы не можете совершать действия и реакции",
    reference: "PHB, стр. 290.",
    bullets: [
      "Недееспособное существо не может совершать действия и реакции",
      "Недееспособные существа автоматически проваливают проверки для сопротивления Захвату или Толчку",
      "Существо теряет концентрацию на заклинании, если становится недееспособным",
    ],
  },
  {
    title: "Невидимый",
    icon: "invisible",
    subtitle: "Вас невозможно увидеть",
    description: "Вас невозможно увидеть без помощи магии или особых чувств",
    reference: "PHB, стр. 291.",
    bullets: [
      "С точки зрения скрытности существо считается сильно заслонённым.",
      "Местонахождение существа всё ещё можно определить по шуму, который оно издаёт, или по оставленным им следам.",
      "Вы получаете преимущество на броски атаки.",
      "Броски атаки против вас совершаются с помехой.",
    ],
  },
  {
    title: "Парализованный",
    icon: "internal-injury",
    subtitle: "Вы парализованы",
    description: "Вы неспособны делать что-либо",
    bullets: [
      "Вы недееспособны, а также не способны перемещаться и говорить.",
      "Броски атаки против вас совершаются с преимуществом.",
      "Любая атака, попавшая по вам, считается критическим попаданием, если нападающий находится в пределах 5 футов от существа.",
      "Вы автоматически проваливаете спасброски Силы и Ловкости.",
    ],
  },
  {
    title: "Окаменевший",
    icon: "stone-pile",
    subtitle: "Вы превращены в камень",
    description:
      "Вы, а также все немагические предметы, которые вы несёте или носите, трансформируетесь в твёрдое инертное вещество (как правило, в камень)",
    reference: "PHB, стр. 291.",
    bullets: [
      "Ваш вес увеличивается в 10 раз, и вы перестаёте стареть",
      "You are incapacitated, can't move or speak, and are unaware of your surroundings.",
      "Attack rolls against you have advantage.",
      "You automatically fail Strength and Dexterity saving throws.",
      "You have resistance to all damage.",
      "You are immune to poison and disease, though a poison or disease already in your system is only suspended, not neutralized.",
    ],
  },
  {
    title: "Отравленный",
    icon: "deathcab",
    subtitle: "Вы отравлены",
    description: "Вы отравлены",
    reference: "PHB, стр. 292.",
    bullets: ["Вы совершаете с помехой броски атаки и проверки характеристик."],
  },
  {
    title: "Лежащий",
    icon: "crawl",
    subtitle: "Вы лежите",
    description: "Вы лежите",
    reference: "PHB, стр. 292.",
    bullets: [
      "Your only movement option is to crawl, unless you stand up.",
      "You have disadvantage on attack rolls.",
      "Attack rolls against you have advantage if the attacker is within 5 feet of you, otherwise the attack roll has disadvantage.",
    ],
  },
  {
    title: "Опутанный",
    icon: "imprisoned",
    subtitle: "Вы опутаны",
    description: "Вы опутаны",
    reference: "PHB, стр. 292.",
    bullets: [
      "Your speed becomes 0, and you can't benefit from any bonus to your speed.",
      "You have disadvantage on attack rolls.",
      "Attack rolls against you have advantage.",
      "You have disadvantage on Dexterity saving throws.",
    ],
  },
  {
    title: "Ошеломлённый",
    icon: "internal-injury",
    subtitle: "Вы ошеломлены",
    description: "Вы ошеломлены",
    reference: "PHB, стр. 292.",
    bullets: [
      "You are incapacitated, can't move, and can speak only falteringly.",
      "Attack rolls against you have advantage.",
      "You automatically fail Strength and Dexterity saving throws.",
    ],
  },
  {
    title: "Бессознательный",
    icon: "coma",
    subtitle: "Вы без сознания",
    description: "Вы без сознания",
    reference: "PHB, стр. 292.",
    bullets: [
      "You are incapacitated, can't move or speak, and are unaware of your surroundings.",
      "You drop whatever you're holding and fall prone.",
      "Attack rolls against you have advantage.",
      "Any attack that hits you is a critical hit if the attacker is within 5 feet of you.",
      "You automatically fail Strength and Dexterity saving throws.",
    ],
  },
  {
    title: "Умирающий",
    icon: "dead-head",
    subtitle: "Вы умираете",
    description: "Ваши хиты снижены до нуля и вы умираете",
    reference: "PHB, стр. 197.",
    bullets: [
      "If you are reduced to 0 hit points by damage that fails to kill you, you fall unconscious and are dying.",
      "If you receive any healing you immediately regain consciousness again and no longer dying.",
      "When dying, at the start of each of your turns you make a death saving throw. Roll a d20 and do not add any modifiers.",
      "A 10 or higher is a success, 9 or lower is a failure.",
      "On your third success, you become stable.",
      "On your third failure, you die.",
      "Rolling a 1 counts as two failures.",
      "Rolling a 20 immediately causes you to regain 1 hit point.",
      "You can also be stabilized by an ally taking the Stabilize action and succeeding on a DC 10 Wisdom (Medicine) check.",
      "Once stable, you regain 1 hit point after 1d4 hours.",
    ],
  },
];
